# Generated by Django 5.2.1 on 2025-06-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
